name: Dergons
main: no.runsafe.dergons.Dergons
version: 1.0.@BUILD@
author: Kruithne, DevelopDeborah
depend: [RunsafeWorldGuardBridge]
description: They aren't dragons
commands:
  dergons:
    description: Dergon related commands